"""TestDates

Revision ID: ea583fb4fd92
Revises: 
Create Date: 2021-10-02 09:15:57.757303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea583fb4fd92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('urole', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memb_account',
    sa.Column('varClientKey', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phys_address', sa.String(length=50), nullable=True),
    sa.Column('phys_city', sa.String(length=50), nullable=True),
    sa.Column('phys_state', sa.String(length=50), nullable=True),
    sa.Column('phys_zip', sa.String(length=50), nullable=True),
    sa.Column('mail_address', sa.String(length=50), nullable=True),
    sa.Column('mail_city', sa.String(length=50), nullable=True),
    sa.Column('mail_state', sa.String(length=50), nullable=True),
    sa.Column('mail_zip', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('varClientKey')
    )
    op.create_table('acct_loans',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('varClientKey', sa.Integer(), nullable=True),
    sa.Column('loan_numb', sa.String(length=25), nullable=True),
    sa.Column('acctnolnno', sa.Integer(), nullable=True),
    sa.Column('balance', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['varClientKey'], ['memb_account.varClientKey'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alert',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('varClientKey', sa.Integer(), nullable=True),
    sa.Column('Alert_Cat', sa.String(length=20), nullable=True),
    sa.Column('varEnteredBy', sa.String(length=100), nullable=True),
    sa.Column('dateEntered', sa.DateTime(), nullable=True),
    sa.Column('Alert_Detail', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['varClientKey'], ['memb_account.varClientKey'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_alert_dateEntered'), 'alert', ['dateEntered'], unique=False)
    op.create_table('follow_up',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('varClientKey', sa.Integer(), nullable=True),
    sa.Column('varEnteredBy', sa.String(length=100), nullable=True),
    sa.Column('dateEntered', sa.DateTime(), nullable=True),
    sa.Column('txtDetails', sa.String(length=5000), nullable=True),
    sa.Column('varLoanNo', sa.String(length=25), nullable=True),
    sa.Column('delq_days', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['varClientKey'], ['memb_account.varClientKey'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_follow_up_dateEntered'), 'follow_up', ['dateEntered'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_dateEntered'), table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index(op.f('ix_alert_dateEntered'), table_name='alert')
    op.drop_table('alert')
    op.drop_table('acct_loans')
    op.drop_table('memb_account')
    op.drop_table('Usr')
    # ### end Alembic commands ###
